
/**
 * 
 * autogenerated by solidity-visual-auditor
 * 
 * execute with: 
 *  #> truffle test <./solidity/test/test.js>
 * 
 * */
var KipuBank = artifacts.require("./solidity/KipuBank.sol");

contract('KipuBank', (accounts) => {
    var creatorAddress = accounts[0];
    var firstOwnerAddress = accounts[1];
    var secondOwnerAddress = accounts[2];
    var externalAddress = accounts[3];
    var unprivilegedAddress = accounts[4]
    /* create named accounts for contract roles */

    before(async () => {
        /* before tests */
    })

    beforeEach(async () => {
        /* before each context */
    })

    it('should revert if ...', () => {
        return KipuBank.deployed()
            .then(instance => {
                return instance.publicOrExternalContractMethod(argument1, argument2, { from: externalAddress });
            })
            .then(result => {
                assert.fail();
            })
            .catch(error => {
                assert.notEqual(error.message, "assert.fail()", "Reason ...");
            });
    });

    context('testgroup - security tests - description...', () => {
        //deploy a new contract
        before(async () => {
            /* before tests */
            const newKipuBank = await KipuBank.new()
        })


        beforeEach(async () => {
            /* before each tests */
        })



        it('fails on initialize ...', async () => {
            return assertRevert(async () => {
                await newKipuBank.initialize()
            })
        })

        it('checks if method returns true', async () => {
            assert.isTrue(await newKipuBank.thisMethodShouldReturnTrue())
        })
    })
});
